pipeline{
  agent{
    docker {
      image "gcc-analyse"
      args "-v /var/lib/jenkins/workspace/gcc-analyse/demo3:/home/gcc-analyse/demo"
    }
  }
  stages{
    stage("Lint test"){
      steps{
        sh "clang-format --dry-run --Werror /home/gcc-analyse/demo/demo.c"
      }
    }
    stage("Static Analyse"){
      steps{
        sh "cppcheck /home/gcc-analyse/demo/demo.c --enable=all --addon=/home/Misra/misra.json --xml > report.xml"
      }
    }
    stage("Build"){
      steps{
        sh "pwd"
        sh "./demo/make"
      }
    }
  }
}
